Screen
DesApp-2023c3-Grupo-3/BulletinBoardServer pull request #22
Opened 2023-10-01 18:55 UTC by ValentinoChiappanni

2023-10-02 18:31 UTC, tomas0011 requested changes

2023-10-02 18:31 UTC, tomas0011 commented on src/entities/screen.entity.ts
> +  templeteId: string;
Por que sacas la columna subscription? esa aun no se depreco

2023-10-02 18:31 UTC, tomas0011 commented on src/entities/screen.entity.ts
Te haria falta agregar el sectorId

2023-10-03 23:55 UTC, ValentinoChiappanni commented on src/entities/screen.entity.ts
Esta!

2023-10-06 15:49 UTC, tomas0011 requested changes
Hay que tipar el output de los servicios y de los controladores
EJ:
```js
async findAll(): Promise<Screen[]> {}
async findOne(): Promise<Screen> {}
```

2023-10-06 15:49 UTC, tomas0011 commented on src/resources/screen/screen.service.ts
>    async findAll() {
Tanto aca como en el findOne requerimos que se filtre por deletedAt

2023-10-06 18:52 UTC, merged