Correccion de donde corren las migraciones
DesApp-2023c3-Grupo-3/BulletinBoardServer pull request #44
Opened 2023-10-24 02:44 UTC by ValentinoChiappanni

2023-10-30 19:33 UTC, tomas0011 requested changes

2023-10-30 19:33 UTC, tomas0011 commented on package.json
> +    "db:migrate:produ": "npm run typeorm:produ migration:run",
db:migrate:prod

2023-10-30 19:33 UTC, tomas0011 commented on src/database/data-source.ts
> +  migrations: ['dist/database/migrations/*{.ts,.js}'],
Ya te habia comunicado mi desconfianza de esto

2023-11-01 22:10 UTC, ValentinoChiappanni commented on src/database/data-source.ts
> +  migrations: ['dist/database/migrations/*{.ts,.js}'],
Esta todo contemplado, no falla.

2023-11-01 22:11 UTC, ValentinoChiappanni commented on package.json
> +    "db:migrate:produ": "npm run typeorm:produ migration:run",
ok

2023-11-06 20:01 UTC, merged